/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import logica.InformacionLogica;
import logica.IntegranteLogica;
import modelo.Informacion;
import modelo.Integrante;

/**
 *
 * @author Konita
 */
public class PanelRegistrarInformacion extends javax.swing.JPanel {

    IntegranteLogica integranteLogica;
    InformacionLogica informacionLogica;
    /**
     * Creates new form PanelInformacion
     */
    public PanelRegistrarInformacion() {
        integranteLogica = new IntegranteLogica();
        informacionLogica = new InformacionLogica();
        initComponents();
        String descripciones[] = {"", "Minas antipersonales(MAP)", "Artefacto explosivo improvisado(AEI)", "Municion sin explotar (MUSE)", "Restos explosivos de guerra(REG)"};
        String estados[] = {"", "Activo", "Inactivo"};
        for (int i = 0; i < estados.length; i++) {
            estadoComboBox.addItem(estados[i]);
        }
        for (int i = 0; i < descripciones.length; i++) {
            descripcionComboBox.addItem(descripciones[i]);
        }
        modificarTitulo.setVisible(false);
        modificarBoton.setVisible(false);
        idText.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarTitulo = new javax.swing.JLabel();
        cedulaLabel = new javax.swing.JLabel();
        descripcionLabel = new javax.swing.JLabel();
        cantidadLabel = new javax.swing.JLabel();
        ubicacionLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        registrarBoton = new javax.swing.JButton();
        cedulaText = new javax.swing.JTextField();
        ubicacionText = new javax.swing.JTextField();
        cantidadSpinner = new javax.swing.JSpinner();
        estadoComboBox = new javax.swing.JComboBox<>();
        descripcionComboBox = new javax.swing.JComboBox<>();
        modificarBoton = new javax.swing.JButton();
        modificarTitulo = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(500, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        registrarTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarTitulo.setText("Registrar Información");
        add(registrarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 240, -1));

        cedulaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cedulaLabel.setText("Numero de identificacion del integrante:");
        add(cedulaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        descripcionLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descripcionLabel.setText("Tipo de artefactos explosivos: ");
        add(descripcionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 171, -1));

        cantidadLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cantidadLabel.setText("Cantidad:");
        add(cantidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 171, -1));

        ubicacionLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ubicacionLabel.setText("Ubicación:");
        add(ubicacionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 171, -1));

        estadoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        estadoLabel.setText("Estado:");
        add(estadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 171, -1));

        registrarBoton.setText("Registrar");
        registrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBotonActionPerformed(evt);
            }
        });
        add(registrarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 88, -1));
        add(cedulaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 240, -1));
        add(ubicacionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 240, -1));

        cantidadSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        add(cantidadSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 240, -1));

        add(estadoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 240, -1));

        descripcionComboBox.setToolTipText("");
        add(descripcionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 240, -1));

        modificarBoton.setText("Modificar");
        modificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBotonActionPerformed(evt);
            }
        });
        add(modificarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 83, -1));

        modificarTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        modificarTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificarTitulo.setText("Modificar Información");
        add(modificarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 220, 20));
        add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 50, -1));
    }// </editor-fold>//GEN-END:initComponents

    public JSpinner getCantidadSpinner() {
        return cantidadSpinner;
    }

    public JTextField getCedulaText() {
        return cedulaText;
    }

    public JComboBox<String> getDescripcionComboBox() {
        return descripcionComboBox;
    }

    public JComboBox<String> getEstadoComboBox() {
        return estadoComboBox;
    }

    public JButton getRegistrarBoton() {
        return registrarBoton;
    }

    public JTextField getUbicacionText() {
        return ubicacionText;
    }

    public JButton getModificarBoton() {
        return modificarBoton;
    }
    
    public JLabel getRegistrarTitulo() {
        return registrarTitulo;
    }

    public JLabel getModificarTitulo() {
        return modificarTitulo;
    }

    public JTextField getIdText() {
        return idText;
    }
    
    

    private void registrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBotonActionPerformed
        try{
            Integrante integrante = integranteLogica.buscarIntegrante(Integer.parseInt(cedulaText.getText()));
            Informacion info = new Informacion();
            info.setCedulaIntegrante(integrante);
            try{
                descripcionComboBox.getSelectedItem().toString().charAt(0);
                info.setDescripcionInformacion(descripcionComboBox.getSelectedItem().toString());
                info.setCantidadInformacion((Integer)cantidadSpinner.getValue());
                try{
                    ubicacionText.getText().charAt(0);
                    info.setUbicacionInformacion(ubicacionText.getText());
                    try{
                       estadoComboBox.getSelectedItem().toString().charAt(0);
                       info.setEstadoInformacion(estadoComboBox.getSelectedItem().toString()); 
                       informacionLogica.registrarInformacion(info);
                       int respuesta = JOptionPane.showConfirmDialog(null, "La informacion ha sido registrada exitosamente. "
                               + "¿Desea seguir registrando con el mismo integrante?", "Registro exitoso", JOptionPane.YES_NO_OPTION);
                       if(respuesta == 0){
                           ubicacionText.setText("");
                           cantidadSpinner.setValue(1);
                           descripcionComboBox.setSelectedIndex(0);
                           estadoComboBox.setSelectedIndex(0);
                       }else{
                           cedulaText.setText("");
                           ubicacionText.setText("");
                           cantidadSpinner.setValue(1);
                           descripcionComboBox.setSelectedIndex(0);
                           estadoComboBox.setSelectedIndex(0);
                       }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(this, "Seleccione algún estado");
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Introduzca una ubicación");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Seleccione algún tipo");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "La cedula no se encuentra registrada, digitela nuevamente");
            cedulaText.setText("");
        }
        
    }//GEN-LAST:event_registrarBotonActionPerformed

    private void modificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBotonActionPerformed
        
        Integrante integrante = integranteLogica.buscarIntegrante(Integer.parseInt(cedulaText.getText()));
        Informacion info = new Informacion();
        info.setCedulaIntegrante(integrante);
        info.setIdInformacion(Integer.parseInt(idText.getText()));
        try{
            descripcionComboBox.getSelectedItem().toString().charAt(0);
            info.setDescripcionInformacion(descripcionComboBox.getSelectedItem().toString());
            info.setCantidadInformacion((Integer)cantidadSpinner.getValue());
            try{
                ubicacionText.getText().charAt(0);
                info.setUbicacionInformacion(ubicacionText.getText());
                try{
                    estadoComboBox.getSelectedItem().toString().charAt(0);
                    info.setEstadoInformacion(estadoComboBox.getSelectedItem().toString()); 
                    informacionLogica.modificarInformacion(info);
                    ubicacionText.setText("");
                    cantidadSpinner.setValue(1);
                    descripcionComboBox.setSelectedIndex(0);
                    estadoComboBox.setSelectedIndex(0);
                    JOptionPane.showMessageDialog(this, "La modificación fue realizada exitosamente");
                    //this.wait(1000);
                    
                    
                    
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Seleccione algún estado");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Introduzca una ubicación");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione algún tipo");
        }
    }//GEN-LAST:event_modificarBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JSpinner cantidadSpinner;
    private javax.swing.JLabel cedulaLabel;
    private javax.swing.JTextField cedulaText;
    private javax.swing.JComboBox<String> descripcionComboBox;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JTextField idText;
    private javax.swing.JButton modificarBoton;
    private javax.swing.JLabel modificarTitulo;
    private javax.swing.JButton registrarBoton;
    private javax.swing.JLabel registrarTitulo;
    private javax.swing.JLabel ubicacionLabel;
    private javax.swing.JTextField ubicacionText;
    // End of variables declaration//GEN-END:variables
}
