/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Jhon
 */
public class PenaPanel extends javax.swing.JPanel {

    /**
     * Creates new form PenaPanel
     */
    public PenaPanel() {
        
        
        initComponents();
        this.setSize(540,320);
        ComboBoxTipoPena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Restricción de la libertad", 
                                                                                   "Carcer Ordinaria con recon de culpa", 
                                                                                   "Cárcel Ordinaria sin recon de culpa", 
                                                                                   "Situación por definir" }));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoPenaBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        ComboBoxTipoPena = new javax.swing.JComboBox<>();
        campoAnioPena = new javax.swing.JTextField();
        campoMesesPena = new javax.swing.JTextField();
        labelAniosPena = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoIDIntegrante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonRegistrarPena = new javax.swing.JButton();
        botonConsultarPena = new javax.swing.JButton();
        labelModalidadPena = new javax.swing.JLabel();
        campoModalidadPena = new javax.swing.JTextField();
        labelModalidadPenaAsignada = new javax.swing.JLabel();
        campoAniosAsignados = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        labelAniosAsignados = new javax.swing.JLabel();
        labelMesesAsignados = new javax.swing.JLabel();

        TipoPenaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TipoPenaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoPenaBoxActionPerformed(evt);
            }
        });

        ComboBoxTipoPena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        campoMesesPena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMesesPenaActionPerformed(evt);
            }
        });

        labelAniosPena.setText("Años Pena");

        jLabel1.setText("Meses Pena");

        jLabel2.setText("Cedula Integrante");

        botonRegistrarPena.setText("Registrar");

        botonConsultarPena.setText("Consultar");

        labelModalidadPena.setText("Modalidad de la pena");

        labelModalidadPenaAsignada.setText("Modalidad Pena Asignada");

        labelAniosAsignados.setText("Años Asignados");

        labelMesesAsignados.setText("Meses Asignados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoIDIntegrante, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelModalidadPena))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelModalidadPenaAsignada)
                            .addComponent(botonConsultarPena, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxTipoPena, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelAniosPena)
                                    .addComponent(campoMesesPena)
                                    .addComponent(campoAnioPena))
                                .addGap(34, 34, 34)
                                .addComponent(botonRegistrarPena, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoModalidadPena, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoAniosAsignados)
                                    .addComponent(labelAniosAsignados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelMesesAsignados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIDIntegrante, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConsultarPena, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModalidadPena)
                    .addComponent(labelModalidadPenaAsignada))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoModalidadPena, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(ComboBoxTipoPena))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAniosAsignados)
                            .addComponent(labelMesesAsignados))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoAniosAsignados, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAniosPena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoAnioPena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoMesesPena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botonRegistrarPena, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TipoPenaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoPenaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoPenaBoxActionPerformed

    private void campoMesesPenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMesesPenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMesesPenaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTipoPena;
    private javax.swing.JComboBox<String> TipoPenaBox;
    private javax.swing.JButton botonConsultarPena;
    private javax.swing.JButton botonRegistrarPena;
    private javax.swing.JTextField campoAnioPena;
    private javax.swing.JTextField campoAniosAsignados;
    private javax.swing.JTextField campoIDIntegrante;
    private javax.swing.JTextField campoMesesPena;
    private javax.swing.JTextField campoModalidadPena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelAniosAsignados;
    private javax.swing.JLabel labelAniosPena;
    private javax.swing.JLabel labelMesesAsignados;
    private javax.swing.JLabel labelModalidadPena;
    private javax.swing.JLabel labelModalidadPenaAsignada;
    // End of variables declaration//GEN-END:variables
}
