/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.gestionIngresoAutoridad;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logica.AutoridadLogica;
import logica.IngresoAutoridadLogica;
import logica.ZonaveredalLogica;
import modelo.Autoridad;
import modelo.Autoridadingresazonaveredal;
import modelo.Zonaveredal;

/**
 *
 * @author Jennifer
 */
public class IngresoAutoridadVista extends javax.swing.JPanel {
    JFrame ventana = null;
    ZonaveredalLogica zonaveredalLogica;
    AutoridadLogica autoridadLogica;
    IngresoAutoridadLogica ingresoLogica;
    /**
     * Creates new form IngresoAutoridadVista
     */
    public IngresoAutoridadVista() {
        initComponents();
        zonaveredalLogica = new ZonaveredalLogica();
        autoridadLogica = new AutoridadLogica();
        ingresoLogica  = new IngresoAutoridadLogica();
        jTextFieldFechaIngreso.setEnabled(false);
        jTextFieldFechaSalida.setEnabled(false);
        Calendar calendar = Calendar.getInstance();
        Date fecha = calendar.getTime();
        Date fecha1 = calendar.getTime();
        SimpleDateFormat formatoDeFecha = new SimpleDateFormat("dd/MM/yyyy");
        jTextFieldFechaIngreso.setText(formatoDeFecha.format(fecha));
    }
    
    public void setFrame(JFrame ventana){
        this.ventana = ventana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        ProyectoDSIIPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ProyectoDSIIPU").createEntityManager();
        zonaveredalQuery = java.beans.Beans.isDesignTime() ? null : ProyectoDSIIPUEntityManager.createQuery("SELECT z.nombreZonaVeredal FROM Zonaveredal z");
        zonaveredalList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : zonaveredalQuery.getResultList();
        jLabelTituloGestionIngresos2 = new javax.swing.JLabel();
        jLabelTituloGestionIngresos = new javax.swing.JLabel();
        jLabelZonaVeredal = new javax.swing.JLabel();
        jComboBoxZonasVeredales = new javax.swing.JComboBox<>();
        jLabelIdentificadorAutoridad = new javax.swing.JLabel();
        jTextFieldIdentificarAutoridad = new javax.swing.JTextField();
        jLabelNombreAutoridad = new javax.swing.JLabel();
        jTextFieldNombreAutoridad = new javax.swing.JTextField();
        jLabelMotivoIngreso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMotivoIngreso = new javax.swing.JTextArea();
        jButtonRegistrarIngreso = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFechaIngresoNombre = new javax.swing.JLabel();
        jLabelFechaSalidaNombre = new javax.swing.JLabel();
        jDateChooserIngreso = new com.toedter.calendar.JDateChooser();
        jDateChooserSalida = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFechaIngreso = new javax.swing.JTextField();
        jTextFieldFechaSalida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabelTituloGestionIngresos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloGestionIngresos2.setText(" a las zonas veredales");

        jLabelTituloGestionIngresos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloGestionIngresos.setText("<html><body>Gestión de ingresos de autoridades </body></html>");
        jLabelTituloGestionIngresos.setAlignmentX(0.5F);
        jLabelTituloGestionIngresos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelZonaVeredal.setText("Zona veredal: ");

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, zonaveredalQuery, eLProperty, jComboBoxZonasVeredales);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboBoxZonasVeredales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxZonasVeredalesActionPerformed(evt);
            }
        });

        jLabelIdentificadorAutoridad.setText("Identificador de autoridad:");

        jTextFieldIdentificarAutoridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificarAutoridadActionPerformed(evt);
            }
        });

        jLabelNombreAutoridad.setText("Nombre:");

        jTextFieldNombreAutoridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreAutoridadActionPerformed(evt);
            }
        });

        jLabelMotivoIngreso.setText("Motivo del ingreso:");

        jTextAreaMotivoIngreso.setColumns(20);
        jTextAreaMotivoIngreso.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMotivoIngreso);

        jButtonRegistrarIngreso.setText("Registrar ingreso");
        jButtonRegistrarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarIngresoActionPerformed(evt);
            }
        });

        jButton1.setText("Registrar salida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Consultar ingresos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("a las zonas veredales");

        jLabelFechaIngresoNombre.setText("Fecha de ingreso:");

        jLabelFechaSalidaNombre.setText("Fecha de salida:");

        jLabel2.setText("Fecha de ingreso:");

        jLabel3.setText("Fecha de salida:");

        jTextFieldFechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaIngresoActionPerformed(evt);
            }
        });

        jLabel4.setText("Consultas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMotivoIngreso)
                                    .addComponent(jLabelNombreAutoridad)
                                    .addComponent(jLabelIdentificadorAutoridad)
                                    .addComponent(jLabelZonaVeredal)
                                    .addComponent(jLabelFechaIngresoNombre)
                                    .addComponent(jLabelFechaSalidaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonRegistrarIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(jTextFieldFechaSalida, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNombreAutoridad, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldIdentificarAutoridad, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jComboBoxZonasVeredales, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(1, 1, 1))
                                    .addComponent(jTextFieldFechaIngreso)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTituloGestionIngresos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloGestionIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZonaVeredal)
                    .addComponent(jComboBoxZonasVeredales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdentificadorAutoridad)
                    .addComponent(jTextFieldIdentificarAutoridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreAutoridad)
                    .addComponent(jTextFieldNombreAutoridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMotivoIngreso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonRegistrarIngreso))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaIngresoNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaSalidaNombre))
                .addGap(22, 22, 22)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTituloGestionIngresos.getAccessibleContext().setAccessibleName("<html>Gestión de ingresos de autoridades <br>\na las zonas veredales</html>");

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxZonasVeredalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxZonasVeredalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxZonasVeredalesActionPerformed

    private void jTextFieldIdentificarAutoridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificarAutoridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdentificarAutoridadActionPerformed

    private void jTextFieldNombreAutoridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreAutoridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreAutoridadActionPerformed

    private void jButtonRegistrarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarIngresoActionPerformed
        try {
            Zonaveredal zonaVeredal = zonaveredalLogica.buscarZonaVeredalPorNombre((String)jComboBoxZonasVeredales.getSelectedItem());
            Autoridad autoridad = autoridadLogica.buscarAutoridad(Integer.parseInt(jTextFieldIdentificarAutoridad.getText()));
            if(autoridad == null){
                autoridad = new Autoridad();
                autoridad.setNombreAutoridad(jTextFieldNombreAutoridad.getText());
                autoridad.setIdAutoridad(Integer.parseInt(jTextFieldIdentificarAutoridad.getText()));
                autoridadLogica.registrarAutoridad(autoridad);    
            }
            Autoridadingresazonaveredal ingreso = new Autoridadingresazonaveredal();
            ingreso.setIdAutoridad(autoridad);
            ingreso.setIdZonaVeredal(zonaVeredal);
            ingreso.setIdIngreso(ingresoLogica.buscarSiguienteId());
            ingreso.setMotivoIngreso(jTextAreaMotivoIngreso.getText());
            autoridad.getNombreAutoridad().charAt(1);
            jTextAreaMotivoIngreso.getText().charAt(1);
            ingresoLogica.registrarIngresoAutoridad(ingreso);
            JOptionPane.showMessageDialog(ventana, "Se ha registrado el ingreso satisfactoriamente");
            jTextAreaMotivoIngreso.setText("");
            jTextFieldIdentificarAutoridad.setText("");
            jTextFieldNombreAutoridad.setText("");
            Calendar calendar = Calendar.getInstance();
            Date fecha = calendar.getTime();
            SimpleDateFormat formatoDeFecha = new SimpleDateFormat("dd/MM/yyyy");
            jTextFieldFechaIngreso.setText(formatoDeFecha.format(fecha));
            
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(ventana, "El identificador de autoridad ingresado es incorrecto");
        }catch (StringIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(ventana, "Ningun campo debe estar vacio o incompleto");
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(ventana, ex.getMessage());
        } 
       
    }//GEN-LAST:event_jButtonRegistrarIngresoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Date fechaIngreso = jDateChooserIngreso.getDate();
        Date fechaSalida = jDateChooserSalida.getDate();
        List<Autoridadingresazonaveredal> ingresos;
        if(fechaIngreso != null && fechaSalida != null){
            ingresos = ingresoLogica.buscarPorFecha(fechaIngreso, fechaSalida);
            String datosAMostrar[] = crearListaDesplegable(ingresos);
            String opcion = (String) JOptionPane.showInputDialog(ventana,"Ingresos registrados en ese intervalo:", "Elegir uno para ver detalles",JOptionPane.QUESTION_MESSAGE,
                        null,datosAMostrar, datosAMostrar[0]);
            int seleccion = obtenerSeleccion(datosAMostrar, opcion);
            if(seleccion == -1) JOptionPane.showMessageDialog(ventana, "No se ha seleccionado nada para mostrar");
            else{
                Autoridadingresazonaveredal detalle = ingresos.get(seleccion);
                jComboBoxZonasVeredales.setSelectedIndex(detalle.getIdZonaVeredal().getIdZonaVeredal());
                jComboBoxZonasVeredales.setSelectedItem(jComboBoxZonasVeredales.getItemAt(detalle.getIdZonaVeredal().getIdZonaVeredal()));
            }

        }
        else{
            JOptionPane.showMessageDialog(ventana, "Debe seleccionar un rango de fechas");
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    public int obtenerSeleccion(String ingresos[], String opcion){
         for (int i = 0; i < ingresos.length; i++) {
            if(ingresos[i].equals(opcion)) return i;
        }
        return -1;
    }
    
    public String[] crearListaDesplegable(List<Autoridadingresazonaveredal> ingresos){
        String respuesta[] = new String[ingresos.size()];
        for (int i = 0; i < ingresos.size(); i++) {
            respuesta[i] = "Zona veredal: "+ingresos.get(i).getIdZonaVeredal().getNombreZonaVeredal() + "          Autoridad: " + ingresos.get(i).getIdAutoridad().getNombreAutoridad()
                    +"          Fecha de entrada: "+ ingresos.get(i).getFechaIngreso();
        }
        return respuesta;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Autoridad autoridad = autoridadLogica.buscarAutoridad(Integer.parseInt(jTextFieldIdentificarAutoridad.getText()));
        if(autoridad == null) JOptionPane.showMessageDialog(ventana, "El identificador de autoridad ingresado es incorrecto");
        else{
            try {
                ingresoLogica.registrarSalidaAutoridad(autoridad);
                JOptionPane.showMessageDialog(ventana, "Se ha registrado la salida satisfactoriamente");
                jTextAreaMotivoIngreso.setText("");
                jTextFieldIdentificarAutoridad.setText("");
                jTextFieldNombreAutoridad.setText("");
                Calendar calendar = Calendar.getInstance();
                Date fecha = calendar.getTime();
                SimpleDateFormat formatoDeFecha = new SimpleDateFormat("dd/MM/yyyy");
                jTextFieldFechaIngreso.setText(formatoDeFecha.format(fecha));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(ventana, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaIngresoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager ProyectoDSIIPUEntityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonRegistrarIngreso;
    private javax.swing.JComboBox<String> jComboBoxZonasVeredales;
    private com.toedter.calendar.JDateChooser jDateChooserIngreso;
    private com.toedter.calendar.JDateChooser jDateChooserSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFechaIngresoNombre;
    private javax.swing.JLabel jLabelFechaSalidaNombre;
    private javax.swing.JLabel jLabelIdentificadorAutoridad;
    private javax.swing.JLabel jLabelMotivoIngreso;
    private javax.swing.JLabel jLabelNombreAutoridad;
    private javax.swing.JLabel jLabelTituloGestionIngresos;
    private javax.swing.JLabel jLabelTituloGestionIngresos2;
    private javax.swing.JLabel jLabelZonaVeredal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaMotivoIngreso;
    private javax.swing.JTextField jTextFieldFechaIngreso;
    private javax.swing.JTextField jTextFieldFechaSalida;
    private javax.swing.JTextField jTextFieldIdentificarAutoridad;
    private javax.swing.JTextField jTextFieldNombreAutoridad;
    private java.util.List<modelo.Zonaveredal> zonaveredalList;
    private javax.persistence.Query zonaveredalQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
